### ISSUE TITLE
想咨询一下使用场景

### ISSUE THREAD

**Issue by gujiwuqing** [GreatAuk/plugin-web-update-notification#10]
大佬 这个只能是git自动化部署这种才能吗？如果公司是svn可以解决吗

**Comment by GreatAuk** [comment]
插件是支持多种类型的版本号，你可以用后面三种方式。
* git commit hash（默认）。
* package.json 中的 version 字段。（建议搭配 [bumpp](https://link.juejin.cn/?target=https%3A%2F%2Fgithub.com%2Fantfu%2Fbumpp) 食用最佳）
* build timestamp，运行打包命令时的时间戳。
* custom，用户自定义版本号。

我这周支持下获取  svn 的 Revision Number 吧

**Comment by gujiwuqing** [comment]
好 这个我已经解决 用时间戳了

**Comment by GreatAuk** [comment]
别关了，我把这个 feature 加下，加完你帮我测试下😊，我本地没 svg

**Comment by gujiwuqing** [comment]
> 别关了，我把这个 feature 加下，加完你帮我测试下？😊，我本地没 svg

好的 哈哈哈 好 我还准备说这个解决了所以关了 行 大佬顺便帮我看下umi2的

**Comment by GreatAuk** [comment]
@gujiwuqing 你好，帮我测试下 `v1.4.0` 版本，看下 svn 项目是否生产，新加了个版本类型 `svn_revision_number`。
`svn` 项目下，你不设置 `versionType` 或设置成  `svn_revision_number` 应该都可以生效。
<img width="736" alt="image" src="https://user-images.githubusercontent.com/20253809/225168068-d3a2e1bb-9c73-43f7-bddf-58bebab46f09.png">

**Comment by gujiwuqing** [comment]
> @gujiwuqing 你好，帮我测试下 `v1.4.0` 版本，看下 `svn` 项目是否生效，新加了个版本类型 `svn_revision_number`。 `svn` 项目下，你不设置 `versionType` 或设置成 `svn_revision_number` 应该都可以生效。 <img alt="image" width="736" src="https://user-images.githubusercontent.com/20253809/225168068-d3a2e1bb-9c73-43f7-bddf-58bebab46f09.png">

好的

**Comment by gujiwuqing** [comment]
> > @gujiwuqing 你好，帮我测试下 `v1.4.0` 版本，看下 `svn` 项目是否生效，新加了个版本类型 `svn_revision_number`。 `svn` 项目下，你不设置 `versionType` 或设置成 `svn_revision_number` 应该都可以生效。 <img alt="image" width="736" src="https://user-images.githubusercontent.com/20253809/225168068-d3a2e1bb-9c73-43f7-bddf-58bebab46f09.png">
> 
> 好的
![image](https://user-images.githubusercontent.com/44566835/225181110-fb1e1fdf-cb6d-4ba4-ac2f-dd3a33ed7cde.png)
大佬 嗯 公司项目会自定义打包文件夹 不是必定的dist 所以这个可以配置吗

**Comment by GreatAuk** [comment]
> 自

vite 、umi、webpack ?

**Comment by GreatAuk** [comment]
估计你是 `umi `项目，试下 `v1.4.1`

**Comment by gujiwuqing** [comment]
> 估计你是 `umi `项目，试下 `v1.4.1`

是的 umi 上午在忙 没注意看 我试试
