### ISSUE TITLE
umi2的使用场景

### ISSUE THREAD

**Issue by gujiwuqing** [GreatAuk/plugin-web-update-notification#11]
![image](https://user-images.githubusercontent.com/44566835/224643962-a40c9ce6-37de-4358-a2c8-bd27d8d4e138.png)
![image](https://user-images.githubusercontent.com/44566835/224643991-83ebe470-d997-42c8-b699-a467b36122f6.png)

**Comment by gujiwuqing** [comment]
这个 不太懂ts，所以大佬，如果是ts版本我试了没问题，js版本的话 就一直报错 求大佬指教
![image](https://user-images.githubusercontent.com/44566835/224644369-9ad85fb6-586d-47df-97a5-4d14f25cb494.png)

**Comment by GreatAuk** [comment]
晚上看下，这个插件写的时候，是对照 umi3 的文档写的

**Comment by GreatAuk** [comment]
> 这个 不太懂ts，所以大佬，如果是ts版本我试了没问题，js版本的话 就一直报错 求大佬指教 ![image](https://user-images.githubusercontent.com/44566835/224644369-9ad85fb6-586d-47df-97a5-4d14f25cb494.png)

什么叫 ts 版本的没问题，js 版本报错，其实你 require 的都是 js 代码。
截图看下你说的这两个用法

**Comment by GreatAuk** [comment]
知道你问题了，你用错方法了，而且umi 不用手动导入插件的
```ts
// import { defineConfig} from 'umi'
// import type { Options as WebUpdateNotificationOptions } from '@plugin-web-update-notification/umijs'

export default {
  plugins: ['@plugin-web-update-notification/umijs'],
  webUpdateNotification: {}
}
```

**Comment by gujiwuqing** [comment]
> > 这个 不太懂ts，所以大佬，如果是ts版本我试了没问题，js版本的话 就一直报错 求大佬指教 ![image](https://user-images.githubusercontent.com/44566835/224644369-9ad85fb6-586d-47df-97a5-4d14f25cb494.png)
> 
> 什么叫 ts 版本的没问题，js 版本报错，其实你 require 的都是 js 代码。 截图看下你说的这两个用法

ts版本的就是直接copy文档的代码，js版本 因为没有type类型可言 然后就不能那样子写 然后我看WebUpdateNotificationOptions和这些都是泛型

**Comment by gujiwuqing** [comment]
> 知道你问题了，你用错方法了，而且umi 不用手动导入插件的
> 
> ```ts
> // import { defineConfig} from 'umi'
> // import type { Options as WebUpdateNotificationOptions } from '@plugin-web-update-notification/umijs'
> 
> export default {
>   plugins: ['@plugin-web-update-notification/umijs'],
>   webUpdateNotification: {}
> }
> ```
这样子用吗？我感觉也是会报错的

**Comment by GreatAuk** [comment]
<img width="880" alt="image" src="https://user-images.githubusercontent.com/20253809/224647019-a373ab71-d872-4b73-a898-cf60116863d4.png">
红框内容删了就可以

**Comment by gujiwuqing** [comment]
> <img alt="image" width="880" src="https://user-images.githubusercontent.com/20253809/224647019-a373ab71-d872-4b73-a898-cf60116863d4.png">
> 
> 红框内容删了就可以

呃 我试过了 会报错的 我截图下给你看
![image](https://user-images.githubusercontent.com/44566835/224647600-4df14514-e304-4bf5-a73b-d950f5451456.png)

**Comment by gujiwuqing** [comment]
我猜测可能是版本问题还是什么。。

**Comment by GreatAuk** [comment]
好的，晚上看下

**Comment by gujiwuqing** [comment]
> 好的，晚上看下

![image](https://user-images.githubusercontent.com/44566835/224648902-e007f248-ec12-4659-ba30-bc343c799bd4.png)
我看umi2是这样子的。很痛苦 大概率是版本使用方法问题 麻烦大佬帮忙看看了 谢谢

**Comment by GreatAuk** [comment]
问题解决了吗， ok 的话就 close 了
