### ISSUE TITLE
vite环境安装之后会报一个错误，也不生效

### ISSUE THREAD

**Issue by yumoer** [GreatAuk/plugin-web-update-notification#12]
报错信息：DevTools failed to load source map: Could not load content for http://192.168.1.194:3000/pluginWebUpdateNotice/webUpdateNoticeInjectScript.global.js.map: HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by GreatAuk** [comment]
vite 什么版本？需要更多信息
打包没有为 webUpdateNoticeInjectScript.global.js 生产 map 文件，我后期加下。这个按道理不影响使用，只是打开 chrome devtool 时，chrome 可能会主动加载对应的 js map 文件。

**Comment by GreatAuk** [comment]
v1.5.0 已经把 webUpdateNoticeInjectScript.global.js 的 sourcemap comment 删除了
