### ISSUE TITLE
大佬，运行你examle里的vite版本报错，如何解决啊？

### ISSUE THREAD

**Issue by atlantischen** [GreatAuk/plugin-web-update-notification#14]
<img width="690" alt="image" src="https://user-images.githubusercontent.com/52541580/225235834-e85f4c4e-e9df-4204-96a9-f04432f2faa6.png">

**Comment by GreatAuk** [comment]
vite 的什么版本？

**Comment by GreatAuk** [comment]
example 的 vite 依赖是通过 pnpm 锁定了版本的 ，估计你用的不是 pnpm 安装依赖。看你下安装的版本是多少

**Comment by atlantischen** [comment]
是用的pnpm安装的依赖

**Comment by atlantischen** [comment]
是用的pnpm安装的依赖

**Comment by GreatAuk** [comment]
我本地还是 3.2.4 ， 晚上更新下版本测试下

**Comment by atlantischen** [comment]
好的，但是现在更新页面，重新build，开了个http-server，并没有弹框，是我哪里有问题吗
<img width="590" alt="image" src="https://user-images.githubusercontent.com/52541580/225270683-bda2d5fa-d4b9-4102-81e4-7179aae86768.png">

**Comment by GreatAuk** [comment]
运行 http-server -> 随意更新点代码，然后 commit -> build，之后不要重新运行 http-server。 如果 http-server 能监听到更新的话， 应该就会有提示。

**Comment by atlantischen** [comment]
出来了，但是监听自定义时间会报这个错误
<img width="592" alt="image" src="https://user-images.githubusercontent.com/52541580/225283500-5704b5fb-7383-4993-beab-cf60da02be02.png">

**Comment by GreatAuk** [comment]
> 出来了，但是监听自定义时间会报这个错误 <img alt="image" width="592" src="https://user-images.githubusercontent.com/52541580/225283500-5704b5fb-7383-4993-beab-cf60da02be02.png">

之前的文档有问题，更新如下：
```ts
// other file to listener update event and custom behavior
document.body.addEventListener('plugin_web_update_notice', (e) => {
  const { version, options } = e.detail
  // write some code, show your custom notification and etc.
  alert('System update!')
})
```

如果要 typesafe , 参考下这个
![image](https://user-images.githubusercontent.com/20253809/225341040-f5d39ce7-5f95-4672-a45d-30457c941998.png)
