### ISSUE TITLE
webpack下报错

### ISSUE THREAD

**Issue by xyyaxyy** [GreatAuk/plugin-web-update-notification#15]
require() of ES modules is not supported

**Comment by GreatAuk** [comment]
webpack 什么版本

**Comment by GreatAuk** [comment]
估计你本地的 `node` 版本小于 `13.2`，在 `13.2` 之前的版本中，ES 模块还不是官方支持的特性。 建议升级下你的版本。

**Comment by xyyaxyy** [comment]
是的，我的 node12 的
