### ISSUE TITLE
重置 window.pluginWebUpdateNotice_.onClickRefresh方法不生效

### ISSUE THREAD

**Issue by xyyaxyy** [GreatAuk/plugin-web-update-notification#18]
window.pluginWebUpdateNotice_.onClickRefresh = () => window.location.reload()
我放在 入口文件 main.js 中的，
控制台 console.log(window.pluginWebUpdateNotice_) 也没有

**Comment by GreatAuk** [comment]
<img width="553" alt="image" src="https://user-images.githubusercontent.com/20253809/230265686-6b0f8b34-20cb-43c6-9432-9443dd99f31b.png">
没问题吧，要不你试下

```ts
setTimeout(() => {
  console.log(window.pluginWebUpdateNotice_)
  window.pluginWebUpdateNotice_.onClickRefresh = () => window.location.reload()
}, 0)
```

**Comment by xyyaxyy** [comment]
是的，用setTimeout可以设置成功，但是页面重新加载之后，会再次弹出 notification 提示更新。
相当于会弹出两次提示，我必须再刷新一下页面

**Comment by GreatAuk** [comment]
<img width="759" alt="image" src="https://user-images.githubusercontent.com/20253809/230282295-3904edca-dbdd-4542-8397-e9dbd29b6b7a.png">
应该是因为 `script` 标签的 `defer` 属性导致代码执行时机不对。不过我看现在用 `vite` 之类的新工具打包，是没问题的。
因为其他的 `js` 文件引入方式，也是用的 `type="module"`。
我考虑下是不是把 `defer` 删了

**Comment by GreatAuk** [comment]
方便的话，把你打包后的 `index.html` 截图看下。

**Comment by xyyaxyy** [comment]
![image](https://user-images.githubusercontent.com/55781841/230286415-99fa2f7b-aa6b-46b6-be67-ae99f225666c.png)

vue2的项目

**Comment by GreatAuk** [comment]
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/20253809/230287305-3f755387-3f8e-46c6-8bd9-fcbdb4f591d9.png">

你没改过 `index.html` 吧？这里插件重复注入了代码😅，我想不出什么 bug 会导致这种情况。
还有麻烦把其他的 `script` 引入方式也截图下。

**Comment by GreatAuk** [comment]
试下最新的 v1.5.1

**Comment by xyyaxyy** [comment]
好的，感谢大佬

**Comment by GreatAuk** [comment]
现在默认用 `window.location.reload` 刷新页面，不用自定义。

![image](https://user-images.githubusercontent.com/20253809/230345438-b078b654-f0d5-4288-9f33-1c11c09fbc3f.png)
我还是好奇这个重复注入代码是怎么产生的...。我看你另一个 issue 给我的项目链接是没这种情况的。
