### ISSUE TITLE
Umi, 配置notificationConfig: {placement: 'topRight'}，构建报错ValidationError: "notificationConfig" is not allowed

### ISSUE THREAD

**Issue by ohspring** [GreatAuk/plugin-web-update-notification#20]
Umijs: 3.5.37
@plugin-web-update-notification/umijs: 1.5.1

config.ts配置：
```
plugins: ['@plugin-web-update-notification/umijs'],
webUpdateNotification: {
  logVersion: true,
  notificationProps: {
    title: '📢 系统升级通知',
    description: '系统版本已更新，请刷新页面后使用',
    buttonText: '刷新',
    dismissButtonText: '忽略',
  },
  notificationConfig: {
    placement: 'topRight',
  },
} as WebUpdateNotificationOptions
```

报错：
![image](https://user-images.githubusercontent.com/49606716/231671500-b440e76a-eb7d-4e29-b4c3-0b64da13fd99.png)

删除notificationConfig: {placement: 'topRight'})后则不报错。

**Comment by GreatAuk** [comment]
晚上给你修下，忘加 schema 了

**Comment by GreatAuk** [comment]
https://github.com/GreatAuk/plugin-web-update-notification/releases/tag/v1.5.2
