### ISSUE TITLE
webpack方式接入，vue.config中配置参数无效果

### ISSUE THREAD

**Issue by blak0001111** [GreatAuk/plugin-web-update-notification#22]
之前设置了checkInterval为 5 * 1000，生效了，后面修改了参数如下：
  plugins: [
      new WebUpdateNotificationPlugin({
        logVersion: true,
        checkInterval: 30 * 1000,
        notificationProps: {
          title: '检测到有新的版本！',
          description: '请使用ctrl + F5 刷新页面，然后点击右上角退出当前用户重新登录体验全新内容',
          buttonText: '刷新',
          dismissButtonText: '忽略'
        },
      }),
    ],
请求间隔还是五秒，弹窗文案也没变，还是默认的那一套。不过每次发版都能检测到。也没报错。。是啥问题呢

**Comment by GreatAuk** [comment]
你打个断点，调试下 checkInterval 是多少

**Comment by GreatAuk** [comment]
还真有可能被缓存了（看你 nginx 怎么配置的），你强制刷新下页面估计就可以。
我考虑给注入的文件加一个 hash 值。

**Comment by blak0001111** [comment]
> 还真有可能被缓存了（看你 `nginx` 怎么配置的），你强制刷新下页面估计就可以。 我考虑给注入的文件加一个 `hash` 值。

好主意。

**Comment by GreatAuk** [comment]
所以是被缓存了吗

**Comment by blak0001111** [comment]
我还在想办法调试，这边用了乾坤套的子应用,比较麻烦。我再定位下

**Comment by GreatAuk** [comment]
你可以直接看打包后的文件，里面的值是不是你要的。

**Comment by blak0001111** [comment]
我刷了几遍，生效了。参数也是我要的。。应该就是缓存。
![image](https://user-images.githubusercontent.com/28420734/231967235-149c0a4c-3e34-40ed-9463-6f9940188497.png)

**Comment by GreatAuk** [comment]
你是不是主应用和子应用都有安装这个插件？

**Comment by GreatAuk** [comment]
因为这个插件很多东西直接挂在 window 下，在微前端下面会有问题...

**Comment by blak0001111** [comment]
> 你是不是主应用和子应用都有安装这个插件？

没。我刚看了，就一个子应用有安装。

**Comment by blak0001111** [comment]
> 因为这个插件很多东西直接挂在 window 下，在微前端下面会有问题...

那的确...我还打算把其他子应用也推广下这个插件呢

**Comment by GreatAuk** [comment]
那我想想有没有解决方案

**Comment by blak0001111** [comment]
> 那我想想有没有解决方案

增加一个可选参数 appName: ''       在WebUpdateNotificationPlugin({appName: ''}) 然后在你window.xxx的时候拼上这个 window.appName_xxx

**Comment by GreatAuk** [comment]
我上周末想过，加个命名空间，但对之前代码改动挺大的，可能要升个大版本。
最近是鸽了，五一加吧。

**Comment by GreatAuk** [comment]
文件名 `hash` 在 `v1.6.0` 加了

**Comment by blak0001111** [comment]
我无意中在乾坤里多个子应用都引入了此插件。好像现在可以正常并存了？

**Comment by GreatAuk** [comment]
qiankun 对 window 有沙箱隔离（当前插件有些内容是挂在 window 下的），按道理是没问题的。
