### ISSUE TITLE
默认会显示notification吗?

### ISSUE THREAD

**Issue by vaynevayne** [GreatAuk/plugin-web-update-notification#24]
spa项目 部署以后, 点击路由跳转, 并没有显示notification

**Comment by GreatAuk** [comment]
第一次安装插件后部署？

**Comment by GreatAuk** [comment]
这周有空给加一个配置。

**Comment by GreatAuk** [comment]
https://github.com/GreatAuk/plugin-web-update-notification/commit/43163167f22b5bfffd9deaf08dadb1fa8c0c219c

**Comment by GreatAuk** [comment]
```ts
    webUpdateNotice({
      versionType: "build_timestamp",
      logVersion: (version) => {
        console.log(
          `version: ${new Date(parseInt(version)).toLocaleString("zh-CN")}`
        );
      },
      ...
    }
```

**Comment by vaynevayne** [comment]
qiang

**Comment by GreatAuk** [comment]
这里是用不了 `dayjs` 之类的哈，操作打包是不会把 dayjs 打包进去的。直接写原生吧

**Comment by vaynevayne** [comment]
这段代码是在运行时执行的吧? 那我项目里使用了dayjs, 我就在这里用dayjs 是可以的吧

**Comment by GreatAuk** [comment]
是在运行时执行，但没有参与到主项目的打包过程中。所以是用不了 `dayjs` 的。除非你把 `dayjs` 提前挂到 `window` 下。

**Comment by vaynevayne** [comment]
谢谢, 我可以把dayjs挂到window,
```jsx
// main.js
import dayjs from 'dayjs'

window.dayjs = dayjs
```
 但是怎么保证这个插件是在我挂载了dayjs之后才执行呢?  求科普

**Comment by GreatAuk** [comment]
<img width="995" alt="image" src="https://user-images.githubusercontent.com/20253809/233826819-d3b08442-4687-4645-8689-3879ea577550.png">
只能这样，别折腾了...

**Comment by vaynevayne** [comment]
嗯嗯
