### ISSUE TITLE
Not Support Webpack4 ?

### ISSUE THREAD

**Issue by zuibunan** [GreatAuk/plugin-web-update-notification#26]
https://github.com/GreatAuk/plugin-web-update-notification/blob/master/packages/webpack-plugin/package.json#L43

**Comment by GreatAuk** [comment]
You can try, it seem support

**Comment by GreatAuk** [comment]
sure, next version

**Comment by GreatAuk** [comment]
https://github.com/GreatAuk/plugin-web-update-notification/commit/5935f70546783b4b5182a17b11b05c09a1036cd9
