### ISSUE TITLE
为什么我用umi打包后是..js ..css

### ISSUE THREAD

**Issue by wj0101** [GreatAuk/plugin-web-update-notification#28]
![image](https://user-images.githubusercontent.com/13463968/233905325-b6665414-6b92-44f7-87e4-bd59bcddd3aa.png)
![image](https://user-images.githubusercontent.com/13463968/233905375-d0c3d57a-b90c-4fdf-81cc-1ff90172a83d.png)

**Comment by wj0101** [comment]
补充下是1.6.1的

**Comment by GreatAuk** [comment]
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/20253809/233906168-396376db-7b94-407f-84b1-c9533b5425e4.png">

`umi` 什么版本，我本地没复现。两个点中间其实加的是文件的 `hash` 值。你可以先用 `1.5` 的版本吧。

**Comment by wj0101** [comment]
umi是3.5.38 ，用1.5.3没问题，那就是hash没加上
