### ISSUE TITLE
大佬能不能去掉源码中的?. 可选链 node14以下的用不了

### ISSUE THREAD

**Issue by RAGGA-TIME** [GreatAuk/plugin-web-update-notification#29]
![image](https://user-images.githubusercontent.com/46967109/237019017-65b8d97f-eec6-4617-b739-7c3c6a56ffe1.png)
如果能兼容那么非常感谢！🙇‍

**Comment by GreatAuk** [comment]
升级版本呗... 。现在 18 是稳定版本，最新已经是 20 了。

**Comment by RAGGA-TIME** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by GreatAuk** [comment]
我过两天更新下打包的 `target` ，再顺便 fix 下其他 bug, 到时 @ 你。

**Comment by RAGGA-TIME** [comment]
> 我过两天更新下打包的 `target` ，再顺便 fix 下其他 bug, 到时 @ 你。

感谢大佬！
