### ISSUE TITLE
请问下 webpack@"5.75.0" 是不能使用吗？使用npm安装失败。

### ISSUE THREAD

**Issue by Alic-Chen** [GreatAuk/plugin-web-update-notification#31]
![AT1}FJ5@EVM_5OPG4U7SV`P](https://github.com/GreatAuk/plugin-web-update-notification/assets/76934976/8d15bd3f-5e0d-4b6c-8cf0-8852917956f2)

**Comment by GreatAuk** [comment]
参考这个：https://cloud.tencent.com/developer/article/2113889

目前插件的 `peerDependences` 是这样配置的 https://github.com/GreatAuk/plugin-web-update-notification/blob/b793eb8ec445b573672af4a9361cd9150ea7c47f/packages/webpack-plugin/package.json#L43 不过 `webpack 5` 应该也是支持的。
