### ISSUE TITLE
umi 3.5.0版本用的 最新版1.6.2报错

### ISSUE THREAD

**Issue by AndyShaoxianfeng** [GreatAuk/plugin-web-update-notification#33]
未更新时好的可以输出version，有更新时候报错
![umi报错](https://github.com/GreatAuk/plugin-web-update-notification/assets/13074852/0b143696-fb23-4fca-945c-af64e72b48ae)

**Comment by AndyShaoxianfeng** [comment]
![AAAA](https://github.com/GreatAuk/plugin-web-update-notification/assets/13074852/28c39508-0d6c-4edb-bf5d-af3b23e6f2b9)
![uim](https://github.com/GreatAuk/plugin-web-update-notification/assets/13074852/29fdab64-7a19-4b0c-9704-fb0aed0c875c)

**Comment by GreatAuk** [comment]
<img width="743" alt="image" src="https://github.com/GreatAuk/plugin-web-update-notification/assets/20253809/c785c5c5-c79c-4d8e-a340-863ee945e473">

这个错误是 `fetch` 版本号 json 时报的，你确定这个 `json` 文件没问题吗 。如果方便的话，可以把你们网站链接贴下。
<img width="406" alt="image" src="https://github.com/GreatAuk/plugin-web-update-notification/assets/20253809/02518120-342f-45ec-aca3-a324690397bf">

**Comment by CNlitai** [comment]
同样的错误 vite4版本中

**Comment by GreatAuk** [comment]
> 同样的错误 vite4版本中

方便给个链接看下？

**Comment by GreatAuk** [comment]
试下最新版本
