### ISSUE TITLE
是否可以照顾一下vite 2,3版本的用户?

### ISSUE THREAD

**Issue by 123hyh** [GreatAuk/plugin-web-update-notification#34]
目前我的项目中使用的是vite是 2.9的！请问作者是否有考虑兼容 低版本的vite ？

**Comment by GreatAuk** [comment]
有报错吗？没有使用什么新的 vite api, 应该是支持的。

**Comment by 123hyh** [comment]
支持不了，你的生产依赖定死vite 4以上

**Comment by 123hyh** [comment]
在这个packages/vite-plugin/package.json文件中你定义了

  "peerDependencies": {
    "vite": ">4.0.0"
  },

**Comment by GreatAuk** [comment]
其实你忽略包管理器的 warning 也能用的，我周末更新下。
