### ISSUE TITLE
一直提示更新，感觉有缓存？？？

### ISSUE THREAD

**Issue by zhangdaba** [GreatAuk/plugin-web-update-notification#38]
new WebUpdateNotificationPlugin({
        checkInterval: 1 * 60 * 1000, // 1分钟刷新一次
        logVersion: true,
        checkImmediately: true,
        hiddenDismissButton: true,
        notifyProps: {
          title: '系统更新',
          description: '系统有新版本发布，请刷新界面及时更新！',
          buttonText: '刷新'
        },
        notificationConfig: {
          placement: 'topRight',
          hiddenDismissButton: true
        }
      })
操作步骤：
1、提示升级后，点击了刷新
2、关闭窗口
3、再次打开刚才的界面 
4、还是提示 升级。

**Comment by GreatAuk** [comment]
估计你们的 `index.html` 有缓存啊，建议 `spa` 把缓存都禁用

```nginx
location / {
  index index.html index.htm;
  if ( $uri = '/index.html' ) { # 首页不缓存
    add_header Cache-Control "no-cache, no-store, must-revalidate";
  }
  try_files $uri $uri/ /index.html; # 兼容 history 路由模式，找不到的文件直接重定向到 index.html
}
```

**Comment by zhangdaba** [comment]
页面已经加过了
如下：
  <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
  <meta http-equiv="Pragma" content="no-cache" />
  <meta http-equiv="Expires" content="0" />

>

**Comment by zhangdaba** [comment]
页面已经加过了
如下：
  <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
  <meta http-equiv="Pragma" content="no-cache" />
  <meta http-equiv="Expires" content="0" />

**Comment by GreatAuk** [comment]
会重复提示更新，说明本地的版本号（挂载在 index.html）和远程的版本号不一致。所以八成是 index.html 还有缓存。
如果 `nginx` 已经设置了禁用 index.html 的缓存，那看下 `index.html` 的响应是否有对应的响应头，我估计是 `nginx` 的配置没有生效

**Comment by zhangdaba** [comment]
页面已经加过了
如下：
  <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
  <meta http-equiv="Pragma" content="no-cache" />
  <meta http-equiv="Expires" content="0" />

> 



> 估计你们的 `index.html` 有缓存啊，建议 `spa` 把缓存都禁用
> 
> ```nginx
> location / {
>   index index.html index.htm;
>   if ( $uri = '/index.html' ) { # 首页不缓存
>     add_header Cache-Control "no-cache, no-store, must-revalidate";
>   }
>   try_files $uri $uri/ /index.html; # 兼容 history 路由模式，找不到的文件直接重定向到 index.html
> }
> ```


nginx加过了 ，但是这样做之后，所有界面都不缓存了。。每次刷新都不走缓存了。。
