### ISSUE TITLE
webpack这么配置完并没有logVersion啊！除了在vue.config.js中写了，还写了一个version.json文件，还需要写别的么

### ISSUE THREAD

**Issue by ccccc123ccc** [GreatAuk/plugin-web-update-notification#40]
![image](https://github.com/GreatAuk/plugin-web-update-notification/assets/107553091/9b399a21-448d-458e-b3cf-d00b62d21d53)

**Comment by GreatAuk** [comment]
logVersion 会在控制台输出，如果更新提示都生效了的话，这个应该没问题的
<img width="334" alt="image" src="https://github.com/GreatAuk/plugin-web-update-notification/assets/20253809/6d63cfed-cf74-496e-8b23-ad3aa3bd8a46">

**Comment by GreatAuk** [comment]
1. 打开项目页面
2. 随机提交一个 git commit ，然后打包重新部署
3. 重新回到刚才打开的页面，看有没有提示

**Comment by ccccc123ccc** [comment]
就是重新部署之后才有log出来的版本号，但是并没有提示

**Comment by GreatAuk** [comment]
有提交过 git commit 吗？你可以看下远程的版本和本地版本是否不一样，不一样才会提示
<img width="926" alt="image" src="https://github.com/GreatAuk/plugin-web-update-notification/assets/20253809/075a160f-1c67-4744-80b0-e72d3386e17d">
<img width="341" alt="image" src="https://github.com/GreatAuk/plugin-web-update-notification/assets/20253809/e4d73d8b-fa86-43d7-9f60-7145e9a7d9bd">
