### ISSUE TITLE
我在umi3中使用 项目关闭的时候执行请求api

### ISSUE THREAD

**Issue by shaoxinyu0912** [GreatAuk/plugin-web-update-notification#42]
<img width="2342" alt="image" src="https://github.com/GreatAuk/plugin-web-update-notification/assets/116056134/8b6b50b6-1f86-40ca-a30a-9bb9b2f1ef30">
  webUpdateNotification: {
    // logVersion: true,
    versionType: "build_timestamp",
    checkInterval: 0.5 * 60 * 1000,
    notificationProps: {
      title: 'system update',
      description: 'System update, please refresh the page',
      buttonText: 'refresh',
      dismissButtonText: 'dismiss',
    },
  }
  plugins: ['@plugin-web-update-notification/umijs'],
  真的很诧异。。。

**Comment by shaoxinyu0912** [comment]
项目开着的时候不请求。。 项目关闭了 他开始请求了 。。

**Comment by GreatAuk** [comment]
这个不是插件的请求，然后插件只在生产环境生效

插件请求的是这个 `json` 文件。
<img width="347" alt="image" src="https://github.com/GreatAuk/plugin-web-update-notification/assets/20253809/47b82944-0ab7-42c7-9163-767701fea8dd">
