### ISSUE TITLE
[bug]这个插件是不是会阻塞 react 相关库针对 sessionStorage 的读写?

### ISSUE THREAD

**Issue by vaynevayne** [GreatAuk/plugin-web-update-notification#44]
<img width="1171" alt="image" src="https://github.com/GreatAuk/plugin-web-update-notification/assets/124666577/4c75f744-6e23-43f9-a001-fd63f17932dd">

当有提示时,假如不点或者拒绝刷新,  那么 这个 session 不会有值, 点了之后就会有值

https://mantine.dev/hooks/use-local-storage/
我用的这个 session 库

**Comment by GreatAuk** [comment]
没有，插件的刷新只是简单的 `window.location.reload()`，你可以排查下自己的业务代码

**Comment by vaynevayne** [comment]
还真有问题, 

 我把 useSessionStorage 换成 zustand, 依然有这个问题, 
 而且我在本机上  无论换不换  vite preview是正常的, 
一旦到了线上, session 就 set 不进去了,我移除了这个库, 就好了

**Comment by vaynevayne** [comment]
我做了两件事: 
1. 替换或不替换 hook 到 zustand
2. 移除或不移除本插件
四种情况,我都试过了, 还是在 dev 中看不到这个 session
我感觉跟浏览器有关系? 我先开 dev,再输入 url, 就能看到 session 面板的值, 
先输url,再打开 session 就看不到 session 的值
现在很虚, 不知道数据对不对
你知道怎么回事吗?

**Comment by GreatAuk** [comment]
换个浏览器看下
直接代码读缓存，看 sessionStorage 有没有值
