### ISSUE TITLE
点了刷新按钮, 过几秒又提示需要刷新?

### ISSUE THREAD

**Issue by vaynevayne** [GreatAuk/plugin-web-update-notification#47]
这是什么原因啊? 是不是需要强制刷新之类的?

**Comment by GreatAuk** [comment]
能提供访问地址吗，如果可以提供是最好的了。
八成是 index.html 有缓存。

[参考这个](https://github.com/GreatAuk/plugin-web-update-notification/blob/master/README.zh-CN.md#%E5%BB%BA%E8%AE%AE-%E5%A6%82%E6%9E%9C%E6%98%AF-spa-%E5%BA%94%E7%94%A8%E7%A6%81%E7%94%A8-indexhtml-%E7%9A%84%E7%BC%93%E5%AD%98)

**Comment by vaynevayne** [comment]
好像是缓存了

**Comment by GreatAuk** [comment]
https://github.com/GreatAuk/plugin-web-update-notification/blob/master/README.zh-CN.md#%E5%85%B3%E9%94%AE%E7%A6%81%E7%94%A8-indexhtml-%E7%BC%93%E5%AD%98
