### ISSUE TITLE
vite 打包后 web_version_by_plugin.json 中的version 并没有变动

### ISSUE THREAD

**Issue by taoyao-code** [GreatAuk/plugin-web-update-notification#48]

**Comment by GreatAuk** [comment]
version 默认取的是 `git commit hash`。第一次打包发布后，更新了代码，需要 `git commit` 提交代码生成新的 `hash` 值，version 才会更新。否则 version 还是第一次打包对应的 `commit hash`

**Comment by taoyao-code** [comment]
好的，感谢解答🙏
