### ISSUE TITLE
Refresh page when new versions comes

### ISSUE THREAD

**Issue by Satont** [GreatAuk/plugin-web-update-notification#49]
I'd like have option to refresh page via api or as option, because some of pages should be always up-to-date.

**Comment by GreatAuk** [comment]
<img width="882" alt="image" src="https://github.com/GreatAuk/plugin-web-update-notification/assets/20253809/a26b4c5c-8e78-4a86-a644-4730579dcc06">

**Comment by Satont** [comment]
Oops, i'm totally missed that part of readme.

Thank you.
