### ISSUE TITLE
如何处理多语言场景

### ISSUE THREAD

**Issue by snoopy1412** [GreatAuk/plugin-web-update-notification#5]
尝试了一下，感觉效果很棒，不过针对多语言的场景不知道是否能支持？

**Comment by GreatAuk** [comment]
可以看下[最新版本](https://github.com/GreatAuk/plugin-web-update-notification/releases/tag/v1.0.0)

**Comment by snoopy1412** [comment]
> 

great!

**Comment by yiigoo** [comment]
<link rel="stylesheet" href="/pluginWebUpdateNotice/webUpdateNoticeInjectStyle.css">
<script>console.log('version: %c1757dcb', 'color: #1890ff');</script>
<script>window.pluginWebUpdateNotice_version = '1757dcb';</script>
<script src="/webUpdateNoticeInjectScript.global.js"></script>

umi 打包出来缺少 pluginWebUpdateNotice 路径
