### ISSUE TITLE
vite 5 兼容性

### ISSUE THREAD

**Issue by yulin96** [GreatAuk/plugin-web-update-notification#50]
我很喜欢这个插件，感谢作者。

最近更新vite 5 后打包出现提示：
plugin 'vue-vite-web-update-notice' uses deprecated 'enforce' option. Use 'order' option instead.
plugin 'vue-vite-web-update-notice' uses deprecated 'transform' option. Use 'handler' option instead.

**Comment by GreatAuk** [comment]
周末更新下

**Comment by GreatAuk** [comment]
https://github.com/GreatAuk/plugin-web-update-notification/releases/tag/v1.7.0
