### ISSUE TITLE
用qiankun搭建的微应用可以引入吗，目前我子应用中引入部署后无反应，window上未挂载成功。主应用引入插件，运行时报错

### ISSUE THREAD

**Issue by dingxu369** [GreatAuk/plugin-web-update-notification#54]
![image](https://github.com/GreatAuk/plugin-web-update-notification/assets/51795801/dfb72bf6-2fc8-406e-9a95-b3d322a3abc1)

**Comment by GreatAuk** [comment]
微前端目前应该是不支持的，因为插件目前有些东西是挂在 `window` 下的
