### ISSUE TITLE
关于构建后的疑问

### ISSUE THREAD

**Issue by whenTheMorningDark** [GreatAuk/plugin-web-update-notification#57]
1.我在viteConfig中设置
`
  webUpdateNotice({
      logVersion: true,
      versionType: "build_timestamp"
    })
`
![image](https://github.com/GreatAuk/plugin-web-update-notification/assets/30688843/f5e5bc87-a8fb-4ff9-ace6-cc30fa0a301f)

2. 当我执行npm run build 的时候，发现index.html的window.pluginWebUpdateNotice_version和pluginWebUpdateNotice中的web_version_by_plugin的version字段是一样的
3. 这个时候我刷新页面不会有提示，只有手动的修改了，其中一个的数字才会有改变，我不可能每次构建都手动去修改这其中的某个值把？
4. 这种情况有什么好的建议吗？
5. 我期望的是当我build的时候，就应该这两个都不一样，希望有刷新提示出来

**Comment by GreatAuk** [comment]
你构建时是一样的，但当用户加载 `index.html` 到本地后（用户本地此时存在一个 a 版本）。这里你再构造并发布一版 （b 版本），这里再对比本地和服务端就不一样了

**Comment by whenTheMorningDark** [comment]
> 你构建时是一样的，但当用户加载 `index.html` 到本地后（用户本地此时存在一个 a 版本）。这里你再构造并发布一版 （b 版本），这里再对比本地和服务端就不一样了

get
