### ISSUE TITLE
Incorrect version mismatch when versionType is build_timestamp

### ISSUE THREAD

**Issue by rseligm2** [GreatAuk/plugin-web-update-notification#8]
In the file packages/vite-plugin/src/index.ts, the function webUpdateNotice, line 63 gets the version to put into the json file, line 97 gets the version to put into the index.html file. 

When the versionType is build_timestamp, these two values can be different depending on the speed that the code runs, which causes the update notification to pop up repeatedly even when it should not.

**Comment by GreatAuk** [comment]
In my test example, because the build too fast, they get same timestamp.
This is a low-level issue, thank you for pointing it out.
